name: 'ESLint PR review'
description: 'It lints with ESLint'
branding:
  icon: aperture
  color: blue
author: 'rpkak'
inputs:
  project-root:
    required: false
    description: 'The path of the npm project root'
    default: '.'
  src:
    required: false
    description: 'The path of the source. Relative to project-root'
    default: '.'
  github-token:
    required: true
    description: The GitHub token, to access to this repo
  eslint-format:
    required: false
    description: 'The ESLint format for displaying in log. View https://eslint.org/docs/user-guide/formatters/'
    default: stylish
  approve-mode:
    required: false
    description: 0 for dismissing change-requests, 1 for approving after change-requests, 2 for approving always if ESLint doesn't fail
    default: 0
  extensions:
    required: false
    description: 'Comma separated list of file the fileendings, ESLint should lint.'
    default: js,jsx,ts,tsx
  node-version:
    required: false
    description: 'Version of node for project packages.'
    default: node
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-root }}
    - ${{ inputs.src }}
    - ${{ inputs.github-token }}
    - ${{ inputs.eslint-format }}
    - ${{ inputs.approve-mode }}
    - ${{ inputs.extensions }}
    - ${{ inputs.node-version }}
